### ISSUE TITLE
MalformedTreeException: Overlapping text edits

### ISSUE THREAD

**Issue by otakun** [JnRouvignac/AutoRefactor#130]
Hi.

I tried to use it with default settings. I used it on one big class file. I changed the file name and path, because it's a proprietary company code. Other files of the same module works flawlessly.

I got the following Exception:

```
org.autorefactor.util.UnhandledException: Exception when applying refactorings to file "my/java/file.java": Overlapping text edits
	at org.autorefactor.ui.ApplyRefactoringsJob.run0(ApplyRefactoringsJob.java:127)
	at org.autorefactor.ui.ApplyRefactoringsJob.run(ApplyRefactoringsJob.java:90)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.text.edits.MalformedTreeException: Overlapping text edits
	at org.eclipse.text.edits.TextEdit$InsertionComparator.compare(TextEdit.java:121)
	at java.util.Collections.indexedBinarySearch(Collections.java:332)
	at java.util.Collections.binarySearch(Collections.java:320)
	at org.eclipse.text.edits.TextEdit.computeInsertionIndex(TextEdit.java:796)
	at org.eclipse.text.edits.TextEdit.internalAdd(TextEdit.java:781)
	at org.eclipse.text.edits.TextEdit.addChildren(TextEdit.java:349)
	at org.autorefactor.refactoring.ASTCommentRewriter.addEdits(ASTCommentRewriter.java:134)
	at org.autorefactor.refactoring.Refactorings.applyTo(Refactorings.java:353)
	at org.autorefactor.ui.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:229)
	at org.autorefactor.ui.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:167)
	at org.autorefactor.ui.ApplyRefactoringsJob.run0(ApplyRefactoringsJob.java:123)
	... 2 more
```

**Comment by JnRouvignac** [comment]
Thanks for the bug report.
Two refactoring rules are trying to refactor the same piece of code.
However I cannot do anything without the code that triggered this.

Do you think you could send the file to me privately?
Otherwise, can you trim down the code and try to reduce it to the bare minimum that triggers the problem, then send me an obfuscated version?

**Comment by otakun** [comment]
I try to narrow it down first and then send you a snippet maybe per mail or if it doesn't contain company related stuff then I post it here.

**Comment by JnRouvignac** [comment]
Hello,

Did you make some progress on reproducing the issue with sample code that you can share?

**Comment by otakun** [comment]
Hi,

I just removed code and tried to execute it again and again. After several tries I got following code snippet, which resulted in the error. The autorefactor already added the appends from a previous try.

I guess the problem are the trailing comments, which by the previous developers where used to force a line break for the eclipse formatter (*facepalm*). 

The method names are of course obfuscated :)

```
		StringBuffer sql = new StringBuffer();
		sql.append(", ").append((aggregationType == PREAGGREGATION_NONE
				? translate(entry.getSomething()) : entry.getSomethingElse())//
		).append(", ").append(entry.getIdOfSomething()).append(", "//
		).append(entry.getSomethingElse);
```

**Comment by JnRouvignac** [comment]
> which by the previous developers where used to force a line break for the eclipse formatter (:scream:).

Sad they did not know about `//@formatter:on` and `//@formatter:off` which read much nicer.

**Comment by JnRouvignac** [comment]
Thanks for the detailed bug report!
I could reproduce and fix it.
I also pushed a new nightly if you want to test the result.

Thanks again!
