### ISSUE TITLE
StringBuilderRefactoring - NPE

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#282]
More from the eclipse sources:

```
public StringBuffer printStatement(int indent, StringBuffer output) {
        int length = this.resources.length;
        printIndent(indent, output).append("try" + (length == 0 ? "\n" : " (")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
```

result in the following for the "printIndent" line

```
Caused by: java.lang.NullPointerException
	at org.autorefactor.refactoring.ASTBuilder.copy(ASTBuilder.java:349)
	at org.autorefactor.refactoring.rules.StringBuilderRefactoring.handleTempStringLiterals(StringBuilderRefactoring.java:375)
	at org.autorefactor.refactoring.rules.StringBuilderRefactoring.replaceWithNewStringAppends(StringBuilderRefactoring.java:327)
	at org.autorefactor.refactoring.rules.StringBuilderRefactoring.maybeRefactorAppending(StringBuilderRefactoring.java:162)
	at org.autorefactor.refactoring.rules.StringBuilderRefactoring.visit(StringBuilderRefactoring.java:108)
	at org.autorefactor.refactoring.rules.AggregateASTVisitor.visit(AggregateASTVisitor.java:2379)
	... 53 more
```

**Comment by cal101** [comment]
@Fabrice-TIERCELIN Did you by chance forget to remove some System.out.printlns?
Btw. : Shall I apply AutoRefactor to some more code and report errors the way I did it?

**Comment by cal101** [comment]
https://github.com/JnRouvignac/AutoRefactor/pull/285
