### ISSUE TITLE
JDK9, JDK10 & JDK11 compatibility

### ISSUE THREAD

**Issue by blacelle** [JnRouvignac/AutoRefactor#366]
The plugin installed successfully within Eclipse 4.9, byt AutoRefactor does not apply its magic:

```
eclipse.buildId=4.9.0.I20180906-0745
java.version=11.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_FR
```

```
org.autorefactor.util.UnhandledException: 
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:142)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run0(PrepareApplyRefactoringsJob.java:99)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run(PrepareApplyRefactoringsJob.java:83)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.autorefactor.util.IllegalArgumentException: Invalid version for Release(JavaSE [11])
	at org.autorefactor.refactoring.Release.javaSE(Release.java:84)
	at org.autorefactor.refactoring.Release.javaSE(Release.java:71)
	at org.autorefactor.refactoring.JavaProjectOptionsImpl.<init>(JavaProjectOptionsImpl.java:55)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.getJavaProjectOptions(PrepareApplyRefactoringsJob.java:191)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.addAll(PrepareApplyRefactoringsJob.java:151)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:139)
	... 3 more
```

**Comment by Fabrice-TIERCELIN** [comment]
Currently, AutoRefactor works only from Java 5 to Java 8 :/

**Comment by Fabrice-TIERCELIN** [comment]
The best workaround we can suggest to you is to :
1. Temporary install JDK8
1. Use the JDK8 instead of Java 11 (you will have compile errors)
1. Run AutoRefactor
1. Restore your configuration
1. Then analyze the modifications made by AutoRefactor

PS: Don't forget you can already run the Eclipse built-in rules :
1. Right-click on your project
1. Go on _Source_
1. Click on _Clean up_

**Comment by Fabrice-TIERCELIN** [comment]
Can you try this version and tell me if it works:
[org.autorefactor.plugin-1.3.0-SNAPSHOT.jar.txt](https://github.com/JnRouvignac/AutoRefactor/files/3005008/org.autorefactor.plugin-1.3.0-SNAPSHOT.jar.txt)
[org.autorefactor.plugin.ui-1.3.0-SNAPSHOT.jar.txt](https://github.com/JnRouvignac/AutoRefactor/files/3005009/org.autorefactor.plugin.ui-1.3.0-SNAPSHOT.jar.txt)

To use it:
1. Uninstall AutoRefactor
2. Put the two jars in the eclipse/dropins folder
3. Remove the .txt extension
4. Launch Eclipse

**Comment by Fabrice-TIERCELIN** [comment]
@vogella, can you retry with the latest version?

**Comment by vogella** [comment]
After a new local build I'm not getting an error anymore.

Fabrice TIERCELIN <notifications@github.com> schrieb am Mi., 19. Juni 2019,
20:04:

**Comment by vogella** [comment]
Errror is back, I'm using:   AutoRefactor	1.3.0.201906180902	org.autorefactor.feature.feature.group	null

Strange is that it works if I select only parts of workspace

org.autorefactor.util.UnhandledException: 
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:142)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run0(PrepareApplyRefactoringsJob.java:99)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run(PrepareApplyRefactoringsJob.java:83)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.autorefactor.util.IllegalArgumentException: Invalid version for Release(JavaSE [11])
	at org.autorefactor.refactoring.Release.javaSE(Release.java:84)
	at org.autorefactor.refactoring.Release.javaSE(Release.java:71)
	at org.autorefactor.refactoring.JavaProjectOptionsImpl.<init>(JavaProjectOptionsImpl.java:54)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.getJavaProjectOptions(PrepareApplyRefactoringsJob.java:191)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.addAll(PrepareApplyRefactoringsJob.java:151)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:139)
	... 3 more

The project that seems to trigger this is: 
org.eclipse.swt.opengl.examples from the SWT repo

To test:

git clone https://git.eclipse.org/r/platform/eclipse.platform.swt
import org.eclipse.swt.opengl.examples  into workspace
Run "String" cleanup on it

org.eclipse.swt.opengl.examples has compile errors, so maybe that causes the exception.

**Comment by Fabrice-TIERCELIN** [comment]
I have rewritten the JVM version check. It tests the minor and major number. Can you retry?

**Comment by vogella** [comment]
Thanks, works fine.
