### ISSUE TITLE
Unhandled exception during refactoring

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#398]
Trying to run the "Improve lambda expressions" I get the following error:

org.autorefactor.util.UnhandledException: 
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:142)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run0(PrepareApplyRefactoringsJob.java:99)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.run(PrepareApplyRefactoringsJob.java:83)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.autorefactor.util.IllegalArgumentException: Invalid version for Release(JavaSE [11])
	at org.autorefactor.refactoring.Release.javaSE(Release.java:84)
	at org.autorefactor.refactoring.Release.javaSE(Release.java:71)
	at org.autorefactor.refactoring.JavaProjectOptionsImpl.<init>(JavaProjectOptionsImpl.java:54)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.getJavaProjectOptions(PrepareApplyRefactoringsJob.java:191)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.addAll(PrepareApplyRefactoringsJob.java:151)
	at org.autorefactor.refactoring.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:139)
	... 3 more

**Comment by Fabrice-TIERCELIN** [comment]
Can you run AutoRefactor on a smaller and smaller number of files till you find the code that causes trouble? Then can you provide this code? Is the error appearing on a dialog or in the view "Error log"?

**Comment by Fabrice-TIERCELIN** [comment]
It's a double of #366 Let's talk about it there.
