### ISSUE TITLE
Autorefactoring does not work with Java 13

### ISSUE THREAD

**Issue by vogella** [JnRouvignac/AutoRefactor#427]
Trying to use Autorefactoring with Java 13 results in the following error:

org.autorefactor.util.UnhandledException: 
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:143)
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.run0(PrepareApplyRefactoringsJob.java:100)
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.run(PrepareApplyRefactoringsJob.java:84)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.autorefactor.util.IllegalArgumentException: Invalid version for Release(JavaSE [13])
	at org.autorefactor.jdt.internal.corext.dom.Release.javaSE(Release.java:86)
	at org.autorefactor.jdt.internal.corext.dom.Release.javaSE(Release.java:72)
	at org.autorefactor.jdt.internal.corext.dom.JavaProjectOptionsImpl.<init>(JavaProjectOptionsImpl.java:52)
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.getJavaProjectOptions(PrepareApplyRefactoringsJob.java:192)
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.addAll(PrepareApplyRefactoringsJob.java:152)
	at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:140)
	... 3 more

**Comment by vogella** [comment]
Also the build seems to have issues with Java 13 / Java 12:

mvn clean verify -DskipTests=true

[INFO] Resolving dependencies of MavenProject: org.autorefactor.feature:org.autorefactor.feature:1.3.0-SNAPSHOT @ /home/vogella/git/AutoRefactor/feature/pom.xml
[ERROR] Internal error: java.lang.IllegalArgumentException: Could not find specification for custom execution environment profile 'JavaSE-12' in the target platform -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: Could not find specification for custom execution environment profile 'JavaSE-12' in the target platform

**Comment by vogella** [comment]
And last but not least the build complains if I use Maven 3.6.3 with the following error. Please note that 3.6.3 is fine to use, the 3.6.1 has been fixed with 3.6.3.

Maven 3.6.1 has a bug resolving P2 repositories.

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Maven 3.6.1 has a bug resolving P2 repositories.
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
Cannot build on JDK higher than 8 due to tests failing on more recent JDK.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for parent 1.3.0-SNAPSHOT:
[INFO] 
[INFO] parent ............................................. FAILURE [  0.245 s]
[INFO] org.autorefactor.plugin ............................ SKIPPED
[INFO] org.autorefactor.plugin.ui ......................... SKIPPED
[INFO] org.autorefactor.feature ........................... SKIPPED
[INFO] org.autorefactor.rules.samples ..................... SKIPPED
[INFO] org.autorefactor.plugin.tests ...................... SKIPPED
[INFO] org.autorefactor.repository ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.226 s
[INFO] Finished at: 2020-01-07T15:11:43+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-versions) on project parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]

**Comment by vogella** [comment]
Even if I switch to Java 8 I get the error: I guess some project has Java 13 as BREE. Would be helpful to list the project in the exception

org.autorefactor.util.UnhandledException:
at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.collectRefactoringUnits(PrepareApplyRefactoringsJob.java:143)
at org.autorefactor.jdt.internal.corext.dom.PrepareApplyRefactoringsJob.run0(PrepareApplyRefactoringsJob.java:100)
at

**Comment by cal101** [comment]
https://github.com/JnRouvignac/AutoRefactor/issues/427#issue-546301149 itself does not look
too difficult.
I may be able to help. 
How did you introduce Java 13 in this case?
Just running eclipse using Java 13?
Which version of eclipse?

**Comment by Fabrice-TIERCELIN** [comment]
For Maven, we have switched to Maven 3.7.0 because Maven 3.6.1 seems to be unavailable. We have added Java 13 for running. Although, for build java version, only Java 8 is allowed by default. To compile AutoRefactor with another version, remove those lines in the pom.xml:

```XML
<requireJavaVersion>
	<version>[1.5.0,1.8.1)</version>
	<message>Cannot build on JDK higher than 8 due to tests failing on more recent JDK.</message>
</requireJavaVersion>
```

@vogella, tell me if it's OK now.

**Comment by vogella** [comment]
Looks good to me, the latest local build can be used again for me. Thanks!
