### ISSUE TITLE
RemoveUnnecessaryLocalBeforeReturnCleanUp - ClassCastException

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#432]
Mentioned by @vogella in https://github.com/JnRouvignac/AutoRefactor/issues/404#issuecomment-574361527

org.autorefactor.util.UnhandledException: AbstractExtensionsModel.java:70:41:Visitor org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp is faulty, it will be disabled for the rest of this run.
at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:371)
at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1847)
at org.eclipse.jdt.core.dom.Block.accept0(Block.java:126)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:617)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:447)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:310)
at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:250)
at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:176)
at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run0(ApplyRefactoringsJob.java:117)
at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.run(ApplyRefactoringsJob.java:90)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.ClassCastException: org.eclipse.jdt.core.dom.SimpleType incompatible with org.eclipse.jdt.core.dom.ArrayType
at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp$ReturnStatementVisitor.removeVariable(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:142)
at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp$ReturnStatementVisitor.visit(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:101)
at org.eclipse.jdt.core.dom.ReturnStatement.accept0(ReturnStatement.java:126)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
at org.autorefactor.jdt.internal.ui.fix.RemoveUnnecessaryLocalBeforeReturnCleanUp.visit(RemoveUnnecessaryLocalBeforeReturnCleanUp.java:83)
at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:1843)
... 17 more

 AbstractExtensionsModel is located in the PDE git repo. See https://git.eclipse.org/r/#/admin/projects/pde/eclipse.pde.ui to see how to clone it.

**Comment by cal101** [comment]
The error is caued by an unexpected C style array declaration.

@vogella You wrote about eclipse: 

> We definitely recommend java-style array declaration

I looked at the eclipse guidelines but did not find anything regarding c style array declarations. 
Do you have any pointer on a relevant style guide?

**Comment by vogella** [comment]
We follow the Oracle style guide.

cal <notifications@github.com> schrieb am Sa., 18. Jan. 2020, 22:52:
