### ISSUE TITLE
ReduceIndentationCleanUp is faulty. Caused by: java.lang.ClassCastException: org.eclipse.jdt.core.dom.CatchClause cannot be cast to org.eclipse.jdt.core.dom.Statement

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#443]
When applying rule [org.autorefactor.jdt.internal.ui.fix.ReduceIndentationCleanUp]

to simplified test case

```
class a
{
{
if(false)
{
try
{
throw new Exception();
}
catch(Exception e)
{
}
}
else
;
}
}

```

this leads to

```
org.autorefactor.util.UnhandledException: TestCase.java:4:1:Visitor org.autorefactor.jdt.internal.ui.fix.ReduceIndentationCleanUp is faulty, it will be disabled for the rest of this run.
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:339)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:2222)
    at org.eclipse.jdt.core.dom.IfStatement.accept0(IfStatement.java:178)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
    at org.eclipse.jdt.core.dom.Initializer.accept0(Initializer.java:236)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:447)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:261)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:278)
    at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:255)
    ...
Caused by: java.lang.ClassCastException: org.eclipse.jdt.core.dom.CatchClause cannot be cast to org.eclipse.jdt.core.dom.Statement
    at org.autorefactor.jdt.internal.corext.dom.ASTNodes.fallsThrough(ASTNodes.java:2469)
    at org.autorefactor.jdt.internal.ui.fix.ReduceIndentationCleanUp.visit(ReduceIndentationCleanUp.java:146)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:2218)
    ... 57 more
```

**Comment by cal101** [comment]
Other refactoring seem to fail because of the same base cause:
- OneIfRatherThanDuplicateBlocksThatFallThroughCleanUp
