### ISSUE TITLE
StringBuilderCleanUp is faulty. Caused by: java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#444]
When applying rule [org.autorefactor.jdt.internal.ui.fix.StringBuilderCleanUp]

to simplified test case

```
class I
{
Object t(byte[]q,int l)
{
StringBuilder buf=null;
buf.append(Integer.toHexString(l)+(q));
return 1;
}
}

```

this leads to

```
org.autorefactor.util.UnhandledException: TestCase.java:6:1:Visitor org.autorefactor.jdt.internal.ui.fix.StringBuilderCleanUp is faulty, it will be disabled for the rest of this run.
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:339)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:2456)
    at org.eclipse.jdt.core.dom.MethodInvocation.accept0(MethodInvocation.java:220)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
    at org.eclipse.jdt.core.dom.ExpressionStatement.accept0(ExpressionStatement.java:136)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
    at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:617)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:447)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
    at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:261)
    at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:278)
    at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:255)
    ...
Caused by: java.lang.IllegalArgumentException
    at org.eclipse.jdt.core.dom.ASTNode.checkNewChild(ASTNode.java:2303)
    at org.eclipse.jdt.core.dom.ASTNode$NodeList.add(ASTNode.java:1505)
    at java.util.AbstractList.add(AbstractList.java:108)
    at java.util.Collections.addAll(Collections.java:5455)
    at org.autorefactor.jdt.internal.corext.dom.ASTNodeFactory.addAll(ASTNodeFactory.java:1020)
    at org.autorefactor.jdt.internal.corext.dom.ASTNodeFactory.newMethodInvocation(ASTNodeFactory.java:848)
    at org.autorefactor.jdt.internal.corext.dom.ASTNodeFactory.newMethodInvocation(ASTNodeFactory.java:833)
    at org.autorefactor.jdt.internal.ui.fix.StringBuilderCleanUp.maybeReplaceWithNewStringAppends(StringBuilderCleanUp.java:615)
    at org.autorefactor.jdt.internal.ui.fix.StringBuilderCleanUp.maybeRefactorAppending(StringBuilderCleanUp.java:353)
    at org.autorefactor.jdt.internal.ui.fix.StringBuilderCleanUp.visit(StringBuilderCleanUp.java:302)
    at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:2452)
    ... 61 more
```

**Comment by cal101** [comment]
@Fabrice-TIERCELIN Moin Fabrice! Do you have time for a question on gitter?

**Comment by Fabrice-TIERCELIN** [comment]
I will have time tomorrow.

**Comment by Fabrice-TIERCELIN** [comment]
I'm on Gitter.
