### ISSUE TITLE
StaticInnerClassThanNonStaticCleanUp is faulty - ClassCastException

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#454]
When applying rule [org.autorefactor.jdt.internal.ui.fix.StaticInnerClassThanNonStaticCleanUp]

to simplified test case

```
interface S{static Object q()
{class A{}return 1;}}

```

this leads to

```
org.autorefactor.util.UnhandledException: TestCase.java:2:2:Visitor org.autorefactor.jdt.internal.ui.fix.StaticInnerClassThanNonStaticCleanUp is faulty, it will be disabled for the rest of this run.
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.logFaultyVisitor(AggregateASTVisitor.java:355)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:3071)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:509)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3060)
	at org.eclipse.jdt.core.dom.TypeDeclarationStatement.accept0(TypeDeclarationStatement.java:199)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.Block.accept0(Block.java:128)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:3060)
	at org.eclipse.jdt.core.dom.MethodDeclaration.accept0(MethodDeclaration.java:698)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:526)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3083)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:3012)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.getRefactorings(AggregateASTVisitor.java:283)
	at org.autorefactor.jdt.internal.corext.dom.ApplyRefactoringsJob.applyRefactoring(ApplyRefactoringsJob.java:255)
	...
Caused by: java.lang.ClassCastException: class org.eclipse.jdt.core.dom.ChildPropertyDescriptor cannot be cast to class org.eclipse.jdt.core.dom.ChildListPropertyDescriptor (org.eclipse.jdt.core.dom.ChildPropertyDescriptor and org.eclipse.jdt.core.dom.ChildListPropertyDescriptor are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @31228d83)
	at org.autorefactor.jdt.core.dom.ASTRewrite.getListRewrite(ASTRewrite.java:173)
	at org.autorefactor.jdt.core.dom.ASTRewrite.insertBefore(ASTRewrite.java:410)
	at org.autorefactor.jdt.internal.ui.fix.StaticInnerClassThanNonStaticCleanUp.makeStatic(StaticInnerClassThanNonStaticCleanUp.java:138)
	at org.autorefactor.jdt.internal.ui.fix.StaticInnerClassThanNonStaticCleanUp.visit(StaticInnerClassThanNonStaticCleanUp.java:120)
	at org.autorefactor.jdt.internal.ui.fix.AggregateASTVisitor.visit(AggregateASTVisitor.java:3067)
	... 59 more
```

It may be more appropiate to rename the class to StaticInnerClassRatherThanNonStaticCleanUp or maybe simply MakeInnerClassStatic.

**Comment by Fabrice-TIERCELIN** [comment]
Thank you for this report. I think it's a real bug but I don't plan to fix it as this feature has already been merged into Eclipse and the bug has already been fixed.

So, to avoid this bug, Use the built-in version in _Eclipse 2021-03 M3_ or _Eclipse 2021-03_ instead.

**Comment by cal101** [comment]
I am able to execute cleanups in batch mode now and will disable this autorefactor one based.
Do you have a list which made it into 2020-12 and 2021-03 yet so i don't make useless reports?
I use 2020-12 now and found some bugs.
I will test against nightly before reporting.
Shall I report them standard eclipse way via bugzilla?

**Comment by Fabrice-TIERCELIN** [comment]
All the reports are useful. Any merged rules can still have bugs. You can see the rules that have been merged in:

- _Eclipse 2020-12_ : https://www.eclipse.org/eclipse/news/4.18/jdt.php#JavaEditor
- _Eclipse 2021-03_ : https://www.eclipse.org/eclipse/news/4.19/jdt.php#JavaEditor

Here is the current state of the migration: https://bugs.eclipse.org/bugs/show_bug.cgi?id=570592#c0

You can report anywhere you want.

**Comment by cal101** [comment]
Perfect. Thanks.
